### ISSUE TITLE
Merge Visioneering into the Research Wing / Team of P - Society. 

### ISSUE THREAD

**Issue by sudoankit** [p-society/papers-we-love-bbsr#1]
As discussed with ( I guess ) **core members** of P-Society, I'm creating an issue here to discuss the merging, new focus and power transfers.

#### Power Transfer 
As discussed, I have made @hdidwania an admin for the Visioneering@IIITBH org, please proceed as required ( probably after a discussion )  

#### New Focus

Those who haven't been notified of the breathtaking news, here's it in short, sweet one-liners, bolded for extra pleasure. 

- Visioneering Group is **now maintained by p-society**. 
- Rather than social, research projects, the team will now **host weekly/monthly** ( I don't know ) **paper discussions** on various topics picked by a visioneering member. 
- **Whiteboard** somewhere in the campus to **write down anonymous ideas**.
- A Yearly or ( maybe monthly newspaper ), _The Visioneering Times_ (change the name, as required, I don't give a "insert creative slang" )
- A **blog similar** to [gradient.pub](https://thegradient.pub) or maybe 10% of [distill.pub](https://distill.pub) would be created for updates and clear expositions of papers discussed by each team, the best one in the year could become a submission for [distill.pub's prize](https://distill.pub/prize/) of $10k, go shoot for the stars, IIITians. ( subtle laughter while I write this )
- I also hope, the institute's faculty might support this initiative later on, once it's at least half baked. 

Jokes aside, good luck IIIT! 

I genuinely hope something gonna be lit af.

Ankit.

**Comment by arijeetsat** [comment]
Great @sudoankit  , we all are looking forward to promote research in the college. I guess ,@hdidwania will be forming a focused group for research oriented activities, that will include PWL. @hdidwania I suggest , lets name the research part as Visioneering (like PSoc,TARS)  keeping PWL as collaborating chapter, and lets plan for the events. :+1:

**Comment by hdidwania** [comment]
It is discussed and done. Visioneering is now a part of research wing of IIIT's tech society and will work to promote research culture among the students. We have some exciting plans related to Visioneering, which include formation of paper implementation group (as it started out earlier), and working on publishing group's results in an e-magazine. Visioneering along with PWL and other bodies will hopefully give a major boost to research scenario of the institute. 

The issue can be closed now.
